environment:
  matrix:
    - MYSYSTEM: strawberry
      CACHE: C:\strawberry
      STRBRRY: 1

    # - MYSISTEM: cygwin
    #   BASH: C:\cygwin64\bin\bash
    #   CACHE: C:\cygwin64\var\cache\setup

cache:
  - '%CACHE%'

install:
  - if defined STRBRRY (if not exist "C:\strawberry" choco install strawberryperl -y)
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - if defined STRBRRY (cd %APPVEYOR_BUILD_FOLDER% && cpanm --quiet --installdeps --with-develop --notest .)

build_script:
  - perl Build.PL
  - Build

test_script:
  - Build test