environment:
  matrix:
    - MYSISTEM: cygwin
      BASH: C:\cygwin64\bin\bash
      CACHE: C:\cygwin64\var\cache\setup
      CYG_FLAG: 1
      PERL_MM_USE_DEFAULT: 1
      PERL_EXTUTILS_AUTOINSTALL: "--defaultdeps"
    - MYSYSTEM: strawberry
      CACHE: C:\strawberry
      SBRY_FLAG: 1

cache:
  - '%CACHE%'

install:
  - if defined SBRY_FLAG (if not exist "C:\strawberry" choco install strawberryperl -y)
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - if defined SBRY_FLAG (cd %APPVEYOR_BUILD_FOLDER% && cpanm --quiet --installdeps --with-develop --notest .)
  - if defined CYG_FLAG (choco install cygwin cyg-get)
  - if defined CYG_FLAG (cyg-get perl make libcrypt-devel)
  - if defined CYG_FLAG (%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && perl -MCPAN -e 'install App::cpanminus' && /home/appveyor/perl5/bin/cpanm -v --installdeps --notest .")
build_script:
  - if defined SBRY_FLAG (perl Build.PL && Build)
  - if defined CYG_FLAG (%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && perl Build.PL && ./Build")

test_script:
  - if defined SBRY_FLAG (Build test)
  - if defined CYG_FLAG (%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./Build test")
